// ════════════════════════════════════════════════════════════════════════════
//  DEVICES — GENERATED from the price list. Do not hand-edit.
//
//  Every part in a device category of Config_actelis-price-list.xlsx appears
//  here, so a product can't be missing from the tool just because nobody typed
//  it in. Regenerate with gen_devices.py when a new price list lands.
//
//    model / desc / spec   from the price list (desc is the card-sized summary,
//                          spec the full text shown in the detail view)
//    family / form / icon  from the part's price-list category
//    iface                 a hint derived from the price-list text, used ONLY
//                          for devices absent from AutoRepeaterInfo; everything
//                          in ARI is driven by its real columns instead
//
//  Price, datasheet and filter tab are attached in catalog.js from the price
//  list — they are not repeated here.
// ════════════════════════════════════════════════════════════════════════════

export const DEVICE_ROWS = [
  { pn:"502R20230", model:"CHS-200", family:"CHASSIS", form:"chassis", icon:"chassis",
    desc:"Chassis and accessories for ML230",
    spec:"Chassis and accessories for ML230",
    iface:{copper:false, coax:false, fiber:false, poe:false} },
  { pn:"502R02110", model:"CHS-2000B", family:"CHASSIS", form:"chassis", icon:"chassis",
    desc:"Supporting MLU-64Dx. Includes 19 inch chassis, modules & accessories.",
    spec:"Supporting MLU-64Dx. Includes 19 inch chassis, modules & accessories.",
    iface:{copper:false, coax:false, fiber:false, poe:false} },
  { pn:"503R20132", model:"MLU-32DF", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"32 pairs line card, Front access connection. Compatible with ML230 and ML230\u2026",
    spec:"32 pairs line card, Front access connection. Compatible with ML230 and ML2300.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"503R20232", model:"MLU-32DR", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"32 pairs line card, Rear access connection. Compatible with ML230 and ML2300\u2026",
    spec:"32 pairs line card, Rear access connection. Compatible with ML230 and ML2300.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"503R20164", model:"MLU-64DF", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"64 pairs line card, Front access connection. Compatible with ML230 and ML230\u2026",
    spec:"64 pairs line card, Front access connection. Compatible with ML230 and ML2300. Note: Requires SDU-450 series",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"503R20264", model:"MLU-64DR", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"64 pairs line card, Rear access connection. Compatible with CHS-200 and CHS-\u2026",
    spec:"64 pairs line card, Rear access connection. Compatible with CHS-200 and CHS-2000B. Note: Requires SDU-450 series",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"503R60042", model:"SDU-450", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"Supports ML230/ML2300, 2x 10/100/1000bT + 4xFE/GE uplinks\u2026",
    spec:"Supports ML230/ML2300, 2x 10/100/1000bT + 4xFE/GE uplinks, up to 4 MLU-32/MLU-64 and up to 128 links",
    iface:{copper:false, coax:false, fiber:false, poe:false} },
  { pn:"503R60043", model:"SDU-450G", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"Supports ML230/ML2300, 2x 10/100/1000bT + 4xFE/GE + 4x GE/2.5GE uplinks\u2026",
    spec:"Supports ML230/ML2300, 2x 10/100/1000bT + 4xFE/GE + 4x GE/2.5GE uplinks, up to 4 MLU-32/MLU-64 and up to 128 links",
    iface:{copper:false, coax:false, fiber:false, poe:false} },
  { pn:"503R60041", model:"SDU-455G", family:"CHASSIS", form:"chassis", icon:"card",
    desc:"Supports ML230/ML2300, 2x 10/100/1000bT + 4x GE/2GE uplinks\u2026",
    spec:"Supports ML230/ML2300, 2x 10/100/1000bT + 4x GE/2GE uplinks, up to 4 MLU-32/MLU-64 and up to 128 links. Includes TDM clock distribution - E1/T1, 2MHz, SyncE",
    iface:{copper:false, coax:false, fiber:false, poe:false} },
  { pn:"506R0116R", model:"ML632R", family:"CPE", form:"cpe", icon:"cpe",
    desc:"L3 Switch, Fanless, bonding up to 2 pairs, 4 x10/100BaseT, standard QoS\u2026",
    spec:"L3 Switch, Fanless, bonding up to 2 pairs, 4 x10/100BaseT, standard QoS, ROHS-6 compliant, 12V input.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"506R0146R", model:"ML634R", family:"CPE", form:"cpe", icon:"cpe",
    desc:"L3 Switch, Fanless, bonding up to 4 pairs, 4 x10/100BaseT, standard QoS\u2026",
    spec:"L3 Switch, Fanless, bonding up to 4 pairs, 4 x10/100BaseT, standard QoS, ROHS-6 compliant, 12V input.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"506R61254", model:"GL5010-10J2F", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed Ethernet Switch with 2xGE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed Ethernet Switch with 2xGE SFP Uplinks, 10x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61252", model:"GL5010-8J2F", family:"GL5000", form:"din", icon:"din",
    desc:"10 Port Industrial Managed Ethernet Switch with 2xGE SFP Uplinks\u2026",
    spec:"10 Port Industrial Managed Ethernet Switch with 2xGE SFP Uplinks, 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R62107", model:"GL5010-8J2F-P", family:"GL5000", form:"din", icon:"din",
    desc:"10 Port Industrial Managed PoE Ethernet Switch with 2xGE SFP Uplinks\u2026",
    spec:"10 Port Industrial Managed PoE Ethernet Switch with 2xGE SFP Uplinks, 8x 10/100/1000 Base-T with 8x30W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61253", model:"GL5010-8J4F", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed Ethernet Switch with 4xGE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed Ethernet Switch with 4xGE SFP Uplinks, 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61296", model:"GL5010R-8J2F", family:"GL5000", form:"din", icon:"din",
    desc:"10 Port Industrial Managed L3 Switch with 2xGE SFP Uplinks\u2026",
    spec:"10 Port Industrial Managed L3 Switch with 2xGE SFP Uplinks, 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61255", model:"GL5020-8J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE Ethernet Switch with 4xGE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE Ethernet Switch with 4xGE SFP Uplinks, 8x 10/100/1000 Base-T with 4x30W and 2x90W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R62106", model:"GL5020R-8J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed L3 PoE Ethernet Switch with 4xGE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed L3 PoE Ethernet Switch with 4xGE SFP Uplinks, 8x 10/100/1000 Base-T with 4x30W and 2x90W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61256", model:"GL5020X-8J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T with 4x30W and 2x90W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61257", model:"GL5030X-8J4F", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed Ethernet Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61258", model:"GL5030X-8J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T with 8x30W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61261", model:"GL5030X-8J4F-P1", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T with 4x30W and 2x60W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61262", model:"GL5030X-8J4F-P2", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T with 4x60W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61259", model:"GL5030XR-8J4F", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed L3 Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed L3 Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61260", model:"GL5030XR-8J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE L3 Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE L3 Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T with 8x30W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61306", model:"GL5030XR-8J4F-P1", family:"GL5000", form:"din", icon:"din",
    desc:"12 Port Industrial Managed PoE L3 PIM-SM Switch with 4x10GE SFP Uplinks\u2026",
    spec:"12 Port Industrial Managed PoE L3 PIM-SM Switch with 4x10GE SFP Uplinks, 8x 10/100/1000 Base-T with 8x30W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61309", model:"GL5060-16J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"20 Port Industrial Managed PoE Ethernet Switch with 4xGE SFP Uplinks\u2026",
    spec:"20 Port Industrial Managed PoE Ethernet Switch with 4xGE SFP Uplinks, 16x 10/100/1000 Base-T with 16x30W (240W), DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61264", model:"GL5060X-16J4F", family:"GL5000", form:"din", icon:"din",
    desc:"20 Port Industrial Managed Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"20 Port Industrial Managed Ethernet Switch with 4x10GE SFP Uplinks, 16x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61265", model:"GL5060X-16J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"20 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks\u2026",
    spec:"20 Port Industrial Managed PoE Ethernet Switch with 4x10GE SFP Uplinks, 16x 10/100/1000 Base-T with 16x30W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61267", model:"GL5060XR-16J4F", family:"GL5000", form:"din", icon:"din",
    desc:"20 Port Industrial Managed L3 Switch with 4x10GE SFP Uplinks\u2026",
    spec:"20 Port Industrial Managed L3 Switch with 4x10GE SFP Uplinks, 16x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61268", model:"GL5060XR-16J4F-P", family:"GL5000", form:"din", icon:"din",
    desc:"20 Port Industrial Managed PoE L3 Switch with 4x10GE SFP Uplinks\u2026",
    spec:"20 Port Industrial Managed PoE L3 Switch with 4x10GE SFP Uplinks, 16x 10/100/1000 Base-T with 16x30W, DIN Rail, ROHS-6 compliant, Fanless, 48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61263", model:"GL5070X-8J12F", family:"GL5000", form:"din", icon:"din",
    desc:"8+12 Port Industrial Managed Ethernet Switch with 10G Uplink\u2026",
    spec:"8+12 Port Industrial Managed Ethernet Switch with 10G Uplink , 4x1/10GE SFP+, 8x100/1000Base-FX SFP + 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61295", model:"GL5070XR-8J12F", family:"GL5000", form:"din", icon:"din",
    desc:"8+12 Port Industrial Managed L3 Switch with 10G Uplink , 4x1/10GE SFP+\u2026",
    spec:"8+12 Port Industrial Managed L3 Switch with 10G Uplink , 4x1/10GE SFP+, 8x100/1000Base-FX SFP + 8x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R62108", model:"GL5080X-4J12F", family:"GL5000", form:"din", icon:"din",
    desc:"16 Port Industrial Managed Switch with 12x10GE SFP Uplinks\u2026",
    spec:"16 Port Industrial Managed Switch with 12x10GE SFP Uplinks, 4x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61270", model:"GL5080XR-4J12F", family:"GL5000", form:"din", icon:"din",
    desc:"16 Port Industrial Managed L3 :PIM-SM Switch with 12x10GE SFP Uplinks\u2026",
    spec:"16 Port Industrial Managed L3 :PIM-SM Switch with 12x10GE SFP Uplinks, 4x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-48VDC, redundant dual inputs. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R62011", model:"ML5114D", family:"GL5000", form:"din", icon:"din",
    desc:"14 port Managed Fiber Ethernet switch\u2026",
    spec:"14 port Managed Fiber Ethernet switch, 4x100/1000Base-FX SFP + 10x 10/100/1000 Base-T, DIN Rail, ROHS-6 compliant, Fanless, 12-58V DC, Dual power input, Power supply and SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R62012", model:"ML5114DP", family:"GL5000", form:"din", icon:"din",
    desc:"14 port Managed Fiber Ethernet switch\u2026",
    spec:"14 port Managed Fiber Ethernet switch, 4x100/1000Base-FX SFP + 10x 10/100/1000 Base-T, 240W PoE, DIN Rail, ROHS-6 compliant, Fanless, 12-58V DC, Dual power input, Power supply and SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61287", model:"GL6010X-24J4F-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial Ethernet switch, 24x10/100/1000BT + 4x10GE SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61286", model:"GL6010X-24J4F-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial Ethernet switch, 24x10/100/1000BT + 4x10GE SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61272", model:"GL6010X-24J4F-P-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial PoE Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial PoE Ethernet switch, 24x10/100/1000BT with 24x30W + 4x10G SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61271", model:"GL6010X-24J4F-P-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial PoE Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial PoE Ethernet switch, 24x10/100/1000BT with 24x30W + 4x10G SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61275", model:"GL6010XR-24J4F-P-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial PoE L3 switch\u2026",
    spec:"28 port rack-mounted industrial PoE L3 switch, 24x10/100/1000BT with 24x30W + 4x10G SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61274", model:"GL6010XR-24J4F-P-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial PoE L3 switch\u2026",
    spec:"28 port rack-mounted industrial PoE L3 switch, 24x10/100/1000BT with 24x30W + 4x10G SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61278", model:"GL6020-16J12FC-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial IEC61850/IEEE1613 certified Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial IEC61850/IEEE1613 certified Ethernet switch, 16x10/100/1000BT 8xGE combo ports + 4xGE SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61277", model:"GL6020-16J12FC-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial IEC61850/IEEE1613 certified Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial IEC61850/IEEE1613 certified Ethernet switch, 16x10/100/1000BT 8xGE combo ports + 4xGE SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61284", model:"GL6030-24J4F-P-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial PoE Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial PoE Ethernet switch, 24x10/100/1000BT with 24x30W + 4xGE SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61283", model:"GL6030-24J4F-P-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial PoE Ethernet switch\u2026",
    spec:"28 port rack-mounted industrial PoE Ethernet switch, 24x10/100/1000BT with 24x30W + 4xGE SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61281", model:"GL6031-16J12FC-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial Ethernet switch, 16x10/100/1000BT\u2026",
    spec:"28 port rack-mounted industrial Ethernet switch, 16x10/100/1000BT, 8xGE combo ports + 4xGE SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61280", model:"GL6031-16J12FC-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"28 port rack-mounted industrial Ethernet switch, 16x10/100/1000BT\u2026",
    spec:"28 port rack-mounted industrial Ethernet switch, 16x10/100/1000BT, 8xGE combo ports + 4xGE SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61290", model:"GL6040X-8J28F-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"36 port rack-mounted industrial Ethernet switch, 8x10/100/1000BT\u2026",
    spec:"36 port rack-mounted industrial Ethernet switch, 8x10/100/1000BT, 24xGE SFP + 4x10GE SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61289", model:"GL6040X-8J28F-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"36 port rack-mounted industrial Ethernet switch, 8x10/100/1000BT\u2026",
    spec:"36 port rack-mounted industrial Ethernet switch, 8x10/100/1000BT, 24xGE SFP + 4x10GE SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61293", model:"GL6040XR-8J28F-AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"36 port rack-mounted industrial L3 PIM-SM switch, 8x10/100/1000BT\u2026",
    spec:"36 port rack-mounted industrial L3 PIM-SM switch, 8x10/100/1000BT, 24xGE SFP + 4x10GE SFP, Dual AC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61292", model:"GL6040XR-8J28F-DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"36 port rack-mounted industrial L3 PIM-SM switch, 8x10/100/1000BT\u2026",
    spec:"36 port rack-mounted industrial L3 PIM-SM switch, 8x10/100/1000BT, 24xGE SFP + 4x10GE SFP, Dual DC inputs, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG0530", model:"ML530", family:"GL6000", form:"rack", icon:"rack",
    desc:"Fiber EAD, 4x10/100BaseT+2x100/1000Base-FX, standard QoS, ROHS-6 compliant\u2026",
    spec:"Fiber EAD, 4x10/100BaseT+2x100/1000Base-FX, standard QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG0252", model:"ML540E", family:"GL6000", form:"rack", icon:"rack",
    desc:"Fiber EAD, 4x10/100/1000BaseT+2x100/1000Base-FX, CE2.0, advanced QoS\u2026",
    spec:"Fiber EAD, 4x10/100/1000BaseT+2x100/1000Base-FX, CE2.0, advanced QoS, ROHS-6 compliant,DC-input, SFP should be ordered separately (refer to Type C products), 9K frames support.",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R62006", model:"ML540M AC", family:"GL6000", form:"rack", icon:"rack",
    desc:"10 port Managed Advaced CE2.0 Fiber Ethernet switch\u2026",
    spec:"10 port Managed Advaced CE2.0 Fiber Ethernet switch, 6x100/1000Base-FX SFP + 4x 10/100/1000 Base-T, ROHS-6 compliant, AC power, AC power cable and SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R62016", model:"ML540M DC", family:"GL6000", form:"rack", icon:"rack",
    desc:"10 port Managed Advaced CE2.0 Fiber Ethernet switch\u2026",
    spec:"10 port Managed Advaced CE2.0 Fiber Ethernet switch, 6x100/1000Base-FX SFP + 4x 10/100/1000 Base-T, ROHS-6 compliant, DC power, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"506R61332", model:"GL7006-4J2F-P", family:"GL7000", form:"inpole", icon:"pole",
    desc:"GL7000 in-pole industrial GE switch with 4 x GE RJ45 PoE+ (4x30W) ports\u2026",
    spec:"GL7000 in-pole industrial GE switch with 4 x GE RJ45 PoE+ (4x30W) ports, 2 x SFP 1Gbps ports. IP65. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61329", model:"GL7010-6J4F-P", family:"GL7000", form:"inpole", icon:"pole",
    desc:"GL7000 in-pole industrial GE switch with 6 x GE RJ45 PoE++ ports (2x60W\u2026",
    spec:"GL7000 in-pole industrial GE switch with 6 x GE RJ45 PoE++ ports (2x60W, 4x30W), 4 x SFP 1Gbps ports. IP65. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61330", model:"GL7020-6J4F-P", family:"GL7000", form:"inpole", icon:"pole",
    desc:"GL7000 in-pole industrial GE switch with 6 x GE RJ45 PoE++ ports (2x60W\u2026",
    spec:"GL7000 in-pole industrial GE switch with 6 x GE RJ45 PoE++ ports (2x60W, 4x30W), 4 x SFP 1Gbps ports, I/O controller, Built-In Dali-2 interface and PWM (Power Management). IP65. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"506R61331", model:"GL7030-6J4F-P", family:"GL7000", form:"inpole", icon:"pole",
    desc:"GL7000 in-pole industrial GE switch with 6 x GE RJ45 PoE++ ports (2x60W\u2026",
    spec:"GL7000 in-pole industrial GE switch with 6 x GE RJ45 PoE++ ports (2x60W, 4x30W), 4 x SFP 1Gbps ports, I/O controller, Built-In Dali-2 interface and PWM (Power Management). IP68. SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"501RG0139", model:"GL830-16O", family:"GL800", form:"standalone", icon:"node",
    desc:"6+4 ports, Hybrid PTMP Ethernet aggregation unit, 16 pairs\u2026",
    spec:"6+4 ports, Hybrid PTMP Ethernet aggregation unit, 16 pairs, 4x HSLs (G.FAST/VDSL35B/17A), 4x10/100/1000BaseT+2x1000/2500Base-FX, CE 2.0 advanced H-QoS, SyncE, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0143", model:"GL830-16R", family:"GL800", form:"standalone", icon:"node",
    desc:"6+4 ports, Hybrid Remote Ethernet unit, 16 pairs\u2026",
    spec:"6+4 ports, Hybrid Remote Ethernet unit, 16 pairs, 4x HSLs (G.FAST/VDSL35B/17A), 4x10/100/1000BaseT+2x1000/2500Base-FX, CE 2.0 advanced H-QoS, SyncE, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0140", model:"GL830-8O", family:"GL800", form:"standalone", icon:"node",
    desc:"6+4 ports Hybrid PTMP Ethernet aggregation unit, 8 pairs\u2026",
    spec:"6+4 ports Hybrid PTMP Ethernet aggregation unit, 8 pairs, 4x HSLs (G.FAST/VDSL35B/17A), 4x10/100/1000BaseT+2x1000/2500Base-FX, CE 2.0 advanced H-QoS, SyncE, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0144", model:"GL830-8R", family:"GL800", form:"standalone", icon:"node",
    desc:"6+4 ports Hybrid Remote Ethernet unit, 8 pairs\u2026",
    spec:"6+4 ports Hybrid Remote Ethernet unit, 8 pairs, 4x HSLs (G.FAST/VDSL35B/17A), 4x10/100/1000BaseT+2x1000/2500Base-FX, CE 2.0 advanced H-QoS, SyncE, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0134", model:"GL850L-16O", family:"GL800", form:"standalone", icon:"node",
    desc:"10+8 ports, Hybrid PTMP Ethernet aggregation unit, 16 pairs\u2026",
    spec:"10+8 ports, Hybrid PTMP Ethernet aggregation unit, 16 pairs, 8x HSLs (G.FAST/VDSL35B/17A), 6x10/100/1000BaseT+2x100/1000Base-FX+2x1000/2500Base-FX, CE 2.0 advanced H-QoS, SyncE, Advanced MACsec 256 bit encryption, ROHS-6 compliant, SFP should be ordered s",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0135", model:"GL850L-16R", family:"GL800", form:"standalone", icon:"node",
    desc:"10+8 ports, Hybrid Remote Ethernet unit, 16 pairs\u2026",
    spec:"10+8 ports, Hybrid Remote Ethernet unit, 16 pairs, 8x HSLs (G.FAST/VDSL35B/17A), 6x10/100/1000BaseT+2x100/1000Base-FX+2x1000/2500Base-FX, CE 2.0 advanced H-QoS, SyncE, Advanced MACsec 256 bit encryption, ROHS-6 compliant, SFP should be ordered separately",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"506R61337", model:"GL93C", family:"GL9000CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over coax customer premise equipment. Offering 2xGE RJ45 port.",
    spec:"G.hn over coax customer premise equipment. Offering 2xGE RJ45 port.",
    iface:{copper:false, coax:true, fiber:false, poe:false} },
  { pn:"506R61336", model:"GL93C-W", family:"GL9000CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over coax with integrated WiFi 6 Access point/customer premise equipmen\u2026",
    spec:"G.hn over coax with integrated WiFi 6 Access point/customer premise equipment. Offering 2xGE RJ45 port.",
    iface:{copper:false, coax:true, fiber:false, poe:false} },
  { pn:"506R61335", model:"GL901CS", family:"GL9000HE", form:"rack", icon:"rack",
    desc:"G.hn wave 2 coax SFP to be used with GL9110C.",
    spec:"G.hn wave 2 coax SFP to be used with GL9110C.",
    iface:{copper:false, coax:true, fiber:true, poe:false} },
  { pn:"506R61342", model:"GL9104C", family:"GL9000HE", form:"rack", icon:"rack",
    desc:"PON Extender (G.hn wave 2) indoor switch unit serving up to 64 customers ove\u2026",
    spec:"PON Extender (G.hn wave 2) indoor switch unit serving up to 64 customers over a single Coax or 4 coax ports. Local power. 2.5Gbps uplink (SFP or RJ-45)",
    iface:{copper:false, coax:true, fiber:true, poe:false} },
  { pn:"506R61334", model:"GL9110C", family:"GL9000HE", form:"rack", icon:"rack",
    desc:"PON Extender (G.hn wave 2) indoor switch unit serving up to 160 customers ov\u2026",
    spec:"PON Extender (G.hn wave 2) indoor switch unit serving up to 160 customers over Coax. Local power. 2x 10G PON or Active Eth uplink. GL901CS - G.hn over coax SFP \u2013 to be ordered separately, each can serve up to 16 customers.",
    iface:{copper:false, coax:true, fiber:true, poe:false} },
  { pn:"506R61245", model:"GL91", family:"GL900CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over twisted pair - Customer premises equipment. AC-DC power supply for\u2026",
    spec:"G.hn over twisted pair - Customer premises equipment. AC-DC power supply for the US",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501S61246", model:"GL91T", family:"GL900CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over twisted pair or Coax converter - Customer premises equipment. AC-D\u2026",
    spec:"G.hn over twisted pair or Coax converter - Customer premises equipment. AC-DC power supply for the US",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501S61247", model:"GL91T-RB", family:"GL900CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over twisted pair converter - Customer premises equipment and a reverse\u2026",
    spec:"G.hn over twisted pair converter - Customer premises equipment and a reverse power unit (Lea Networks). AC-DC power supply for the US.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0157", model:"GL92", family:"GL900CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over twisted pair - Customer premise equipment. GE RJ45 port",
    spec:"G.hn over twisted pair - Customer premise equipment. GE RJ45 port",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0158", model:"GL92-R", family:"GL900CPE", form:"cpe", icon:"cpe",
    desc:"G.hn over twisted pair - Customer premise equipment with support for reverse\u2026",
    spec:"G.hn over twisted pair - Customer premise equipment with support for reverse powering. GE RJ45 port",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0167", model:"GL904", family:"GL900HE", form:"standalone", icon:"node",
    desc:"PON Extender (G.hn wave 2) indoor unit serving up to 4 customers over twiste\u2026",
    spec:"PON Extender (G.hn wave 2) indoor unit serving up to 4 customers over twisted pair or Coax. Local power. 1/2.5G PON or Active Eth uplink. Order power supply 506R00008x per your region.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0168", model:"GL904-R", family:"GL900HE", form:"standalone", icon:"node",
    desc:"PON Extender (G.hn wave 2) indoor unit serving up to 4 customers over twiste\u2026",
    spec:"PON Extender (G.hn wave 2) indoor unit serving up to 4 customers over twisted pair or Coax. Local power and reverse power over twisted pairs. 1/2.5G PON or Active Eth uplink. Order power supply 506R00008x per your region.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0303", model:"GL908", family:"GL900HE", form:"standalone", icon:"node",
    desc:"PON Extender (G.hn wave 2) indoor unit serving up to 8 customers over twiste\u2026",
    spec:"PON Extender (G.hn wave 2) indoor unit serving up to 8 customers over twisted pair or Coax. Local power. 1/2.5G PON or Active Eth uplink. Order power supply 506R00008x per your region.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0301", model:"GL908-R", family:"GL900HE", form:"standalone", icon:"node",
    desc:"PON Extender (G.hn wave 2) indoor unit serving up to 8 customers over twiste\u2026",
    spec:"PON Extender (G.hn wave 2) indoor unit serving up to 8 customers over twisted pair or Coax. Local power and reverse power over twisted pairs. 1/2.5G PON or Active Eth uplink. Order power supply 506R00008x per your region.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0302", model:"GL916", family:"GL900HE", form:"standalone", icon:"node",
    desc:"PON Extender (G.hn wave 2) Indoor unit serving up to 16 customers over twist\u2026",
    spec:"PON Extender (G.hn wave 2) Indoor unit serving up to 16 customers over twisted pair or Coax. Local power. 1/2.5G PON or Active Eth uplink. Order power supply 506R00008x per your region.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0300", model:"GL916-R", family:"GL900HE", form:"standalone", icon:"node",
    desc:"PON Extender (G.hn wave 2) indoor unit serving up to 16 customers over twist\u2026",
    spec:"PON Extender (G.hn wave 2) indoor unit serving up to 16 customers over twisted pair or Coax. Local power and reverse power over twisted pairs. 1/2.5G PON or Active Eth uplink. Order power supply 506R00008x per your region",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0016", model:"ML622", family:"ML600", form:"standalone", icon:"node",
    desc:"4+1 port, Managed Hybrid Ethernet Switch\u2026",
    spec:"4+1 port, Managed Hybrid Ethernet Switch, 2 pairs EFM-bonded G.SDHSL Ethernet Extender, 4x10/100BaseT, standard QoS, ROHS-6 compliant",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0121", model:"ML622i with 24/48Vdc", family:"ML600", form:"standalone", icon:"node",
    desc:"4 port, Managed Ethernet Switch, Fanless CPE\u2026",
    spec:"4 port, Managed Ethernet Switch, Fanless CPE, 2 pairs EFM-bonded G.SDHSL Ethernet Extender, 4x10/100BaseT, standard QoS, ROHS-6 compliant, 24/48Vdc power input + power cable",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0046", model:"ML624", family:"ML600", form:"standalone", icon:"node",
    desc:"4+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"4+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs EFM-bonded G.SDHSL Ethernet Extender, 4x10/100BaseT+1 SFP for 100Base-FX, standard QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0122", model:"ML624i with 24/48Vdc", family:"ML600", form:"standalone", icon:"node",
    desc:"4 port, Managed Ethernet Switch, Fanless CPE\u2026",
    spec:"4 port, Managed Ethernet Switch, Fanless CPE, 4 pairs EFM-bonded G.SDHSL Ethernet Extender, 4x10/100BaseT, standard QoS, ROHS-6 compliant, 24/48Vdc power input + power cable",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG0067", model:"ML638", family:"ML600", form:"standalone", icon:"node",
    desc:"5+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"5+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 8 pairs EFM-bonded G.SDHSL Ethernet Extender, 4x10/100BaseT +1x100/1000BaseFX/LX/T, standard QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0218", model:"ML6416E", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 16 pairs EFM-bonded G.SDHSL Ethernet Extender,CE2.0, advanced H-QoS, 4x10/100/1000BaseT+2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0216", model:"ML644E", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Ethernet Switch\u2026",
    spec:"6+1 port, Managed Ethernet Switch, 4 pairs EFM-bonded G.SDHSL Ethernet Extender, CE2.0, advanced H-QoS, 4x10/100/1000BaseT+2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0116", model:"ML644EL", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs EFM-bonded G.SDHSL Ethernet Extender, CE2.0, advanced H-QoS, Advanced MACsec encryption, 4x10/100/1000BaseT+2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0217", model:"ML648E", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 8 pairs EFM-bonded G.SDHSL Ethernet Extender, CE2.0, advanced H-QoS, 4x10/100/1000BaseT+2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0078", model:"ML650SV", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch CES and Clock distribu\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch CES and Clock distribution, 4x10/100BaseT+2x100/1000Base-FX + 4xE1/T1 (converted in PWE), SyncE, advanced QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG0076", model:"ML654S", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs EFM-bonded G.SDHSL Ethernet Extender, CES + Clock distribution, 4x10/100BaseT+2x100/1000Base-FX + 4xE1/T1, SyncE, advanced QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Typ",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0077", model:"ML658S", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 8 pairs EFM-bonded G.SDHSL Ethernet Extender, CES + Clock distribution, 4x10/100BaseT+2x100/1000Base-FX + 4xE1/T1, SyncE, advanced QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Typ",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0477", model:"ML658S Advanced CLK", family:"ML600", form:"standalone", icon:"node",
    desc:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 8 pairs\u2026",
    spec:"6+1 port, Managed Hybrid Fiber/Copper Ethernet Switch, 8 pairs, 4x10/100BaseT+2x100/1000Base-FX + 4xE1/T1, PWE (CESoETH/SATOP/CESoPSN), Independent Differential retiming for E1, SyncE, advanced QoS, ROHS-6 compliant, SFP should be ordered separately (ref",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0106", model:"ML684M", family:"ML600", form:"standalone", icon:"node",
    desc:"5+2 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"5+2 port, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2) Add-Drop EFM-bonded G.SHDSL Ethernet Extender, 4x10/100Base-T+1x100/1000Base-FX SFP, standard QoS, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0238", model:"ML6916E (w/o SyncE)", family:"ML600", form:"standalone", icon:"node",
    desc:"6+4 ports, Compact Ethernet Aggregator,4xHSL\u2026",
    spec:"6+4 ports, Compact Ethernet Aggregator,4xHSL,16 pairs EFM-bonded G.SDHSL Ethernet Extender,CE2.0, advanced H-QoS, 4x10/100/1000BaseT+ 2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0115", model:"ML6916EL", family:"ML600", form:"standalone", icon:"node",
    desc:"6+4 ports, Compact Ethernet Aggregator, 4xHSL\u2026",
    spec:"6+4 ports, Compact Ethernet Aggregator, 4xHSL, 16 pairs EFM-bonded G.SDHSL Ethernet Extender, CE2.0, advanced H-QoS, Advanced MACsec encryption , 4x10/100/1000BaseT+ 2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C pr",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0111", model:"ML6916EN", family:"ML600", form:"standalone", icon:"node",
    desc:"6+16 ports, High Density Ethernet Aggregator,up to 16 HSL\u2026",
    spec:"6+16 ports, High Density Ethernet Aggregator,up to 16 HSL,16 pairs EFM-bonded G.SDHSL Ethernet Extender,CE2.0, 2x 10/100 baseT, 2x10/100/1000BaseT+ 2x100/1000Base-FX, SyncE, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products). ML",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0254", model:"ML6916ES", family:"ML600", form:"standalone", icon:"node",
    desc:"6+4 ports, Compact Ethernet Aggregator, SyncE CLK ,4xHSL,16 pairs,CE2.0\u2026",
    spec:"6+4 ports, Compact Ethernet Aggregator, SyncE CLK ,4xHSL,16 pairs,CE2.0, advanced H-QoS, 4x10/100/1000BaseT+ 2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0259", model:"ML698E", family:"ML600", form:"standalone", icon:"node",
    desc:"6+4 ports, Compact Ethernet Aggregator, 4xHSL\u2026",
    spec:"6+4 ports, Compact Ethernet Aggregator, 4xHSL, 8 pairs EFM-bonded G.SDHSL Ethernet Extender, CE2.0, advanced H-QoS, 4x10/100/1000BaseT+ 2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0253", model:"ML698ES", family:"ML600", form:"standalone", icon:"node",
    desc:"6+4 ports, Compact Ethernet Aggregator, SyncE CLK, 4xHSL\u2026",
    spec:"6+4 ports, Compact Ethernet Aggregator, SyncE CLK, 4xHSL, 8 pairs EFM-bonded G.SDHSL Ethernet Extender, CE2.0, advanced H-QoS, 4x10/100/1000BaseT+ 2x100/1000Base-FX, ROHS-6 compliant, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG0240", model:"ML622D", family:"ML600D", form:"din", icon:"din",
    desc:"2+2 port, Managed Hybrid Copper Ethernet Switch\u2026",
    spec:"2+2 port, Managed Hybrid Copper Ethernet Switch, 2 pairs (1+1 or 1x2) Add-Drop EFM-bonded G.SDHSL Ethernet Extender, 2x10/100Base-T, standard QoS Ethernet Switch and Extender, DIN Rail, ROHS-6 compliant, Fanless, 24/48VDC Single power input",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG3240", model:"ML622D (New)", family:"ML600D", form:"din", icon:"din",
    desc:"2+2 port, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"2+2 port, Managed Hybrid Fiber/Copper Ethernet Switch, 2 pairs (1+1 or 1x2) Add-Drop EFM-bonded G.SDHSL Ethernet Extender, 2x10/100Base-T, standard QoS Ethernet Switch and Extender, DIN Rail, ROHS-6 compliant, Fanless, 24/48VDC, Dual power input.",
    iface:{copper:true, coax:false, fiber:false, poe:false} },
  { pn:"501RG3275", model:"ML680D-M (12/24V)", family:"ML600D", form:"din", icon:"din",
    desc:"8 port, Managed Fiber Ethernet switch\u2026",
    spec:"8 port, Managed Fiber Ethernet switch, 6x10/100/1000Base-T+2x1000Base-FX SFP, DIN Rail, Fanless, 12/24VDC Dual power input, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG0221", model:"ML680DF", family:"ML600D", form:"din", icon:"din",
    desc:"8 port, Managed Fiber Ethernet switch\u2026",
    spec:"8 port, Managed Fiber Ethernet switch, 2x100/1000Base-FX SFP + 6x10/100Base-T, DIN Rail, ROHS-6 compliant, Fanless, 24/48VDC Single Power Input",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG3231", model:"ML680DF (New)", family:"ML600D", form:"din", icon:"din",
    desc:"8 port, Managed Fiber Ethernet switch, 6x10/100Base-T+2x1000Base-FX SFP\u2026",
    spec:"8 port, Managed Fiber Ethernet switch, 6x10/100Base-T+2x1000Base-FX SFP, DIN Rail, Fanless, 24/48VDC Dual power input, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG0236", model:"ML680DFTP", family:"ML600D", form:"din", icon:"din",
    desc:"Managed Fiber Ethernet switch, 2x100/1000Base-FX SFP + 6x10/100Base-T\u2026",
    spec:"Managed Fiber Ethernet switch, 2x100/1000Base-FX SFP + 6x10/100Base-T, Serial server, 2 Passive PoE ports, up to 120W Out, DIN Rail, ROHS-6 compliant, Fanless, 24/48VDC Dual power input, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"501RG3375", model:"ML680DL-M (12/24V)", family:"ML600D", form:"din", icon:"din",
    desc:"10 port, Managed Fiber Ethernet switch\u2026",
    spec:"10 port, Managed Fiber Ethernet switch, 8x10/100/1000Base-T+2x100/1000Base-FX SFP, DIN Rail, Advanced MACSEC Encryption, Fanless, 12/24VDC Dual power input, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:false} },
  { pn:"501RG3378", model:"ML680DLP-M", family:"ML600D", form:"din", icon:"din",
    desc:"10 port, Managed Fiber Ethernet switch\u2026",
    spec:"10 port, Managed Fiber Ethernet switch, 8x10/100/1000Base-T+2x100/1000Base-FX SFP, 2x PoE ports (up to 90W), DIN Rail, Advanced MACSEC Encryption, Fanless, 24/48VDC Dual power input, SFP should be ordered separately (refer to Type C products)",
    iface:{copper:false, coax:false, fiber:true, poe:true} },
  { pn:"501RG0220", model:"ML684D", family:"ML600D", form:"din", icon:"din",
    desc:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2 or 1x4) EFM-bonded G.SHDSL Ethernet Extender, up to 60Mbps, up to 1Mbps@16kft, Ethernet Switch and Extender, 6x10/100Base-T+2x100/1000Base-FX SFP, DIN Rail, ROHS-6 compliant, Fanless, 24",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG3230", model:"ML684D (New)", family:"ML600D", form:"din", icon:"din",
    desc:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2 or 1x4) EFM-bonded G.SHDSL Ethernet Extender, up to 60Mbps, up to 1Mbps@16kft, Ethernet Switch and Extender, 6x10/100Base-T+2x1000Base-FX SFP, DIN Rail, ROHS-6 compliant, Fanless, 24/48V",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG3255", model:"ML684D-M (12/24V)", family:"ML600D", form:"din", icon:"din",
    desc:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2\u2026",
    spec:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2, 1+3 or 1x4) EFM-bonded G.SHDSL, Ethernet Extender, 6x10/100/1000Base-T+2x1000Base-FX SFP, DIN Rail, Fanless, bypass switch, 12/24VDC Dual power input, SFP should be ordered separately",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG3355", model:"ML684DL-M (12/24V)", family:"ML600D", form:"din", icon:"din",
    desc:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2\u2026",
    spec:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2, 1+3 or 1x4) EFM-bonded G.SHDSL Ethernet Extender, 6x10/100/1000Base-T+2x100/1000Base-FX SFP, DIN Rail, Advanced MACSEC Encryption, Fanless, bypass switch, 12/24VDC Dual power input, SF",
    iface:{copper:true, coax:false, fiber:true, poe:false} },
  { pn:"501RG3358", model:"ML684DLP-M", family:"ML600D", form:"din", icon:"din",
    desc:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2\u2026",
    spec:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2, 1+3 or 1x4) EFM-bonded G.SHDSL Ethernet Extender, 6x10/100/1000Base-T +2x100/1000Base-FX SFP, 2x PoE ports (up to 90W), DIN Rail, Advanced MACSEC Encryption, Fanless, bypass switch, 24",
    iface:{copper:true, coax:false, fiber:true, poe:true} },
  { pn:"501RG0232", model:"ML684DTP", family:"ML600D", form:"din", icon:"din",
    desc:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch\u2026",
    spec:"6+2 ports, Managed Hybrid Fiber/Copper Ethernet Switch, 4 pairs (2+2 or 1x4) EFM-bonded G.SDHSL Ethernet Extender, 6x10/100Base-T+2x100/1000Base-FX SFP, Serial server, 2 Passive PoE ports, up to 120W Out, DIN Rail, ROHS-6 compliant, Fanless, 24/48VDC Dua",
    iface:{copper:true, coax:false, fiber:true, poe:true} },
];
